Data Analytics III

1.	Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.
2.	Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset.

In [35]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix ,accuracy_score, classification_report
import seaborn as sns
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import plotly.express as px


In [36]:
temp = sns.load_dataset('iris')
data = pd.DataFrame(temp)
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [37]:
data.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [38]:
X = data.drop('species',axis=1)
y = data['species']

In [39]:
x_train , x_test , y_train ,y_test = train_test_split(X, y , random_state= 8 , test_size= 0.2)

Simple Naïve Bayes classification algorithm


In [40]:
bayes_class = GaussianNB()
bayes_class.fit(x_train,y_train)

GaussianNB()

In [41]:
#Step := for train data prediction
y_pred_train = bayes_class.predict(x_train)

In [42]:
#Step := for test data prediction
y_pred_test = bayes_class.predict(x_test)

Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset.

In [43]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.78      0.78      0.78         9
   virginica       0.82      0.82      0.82        11

    accuracy                           0.87        30
   macro avg       0.87      0.87      0.87        30
weighted avg       0.87      0.87      0.87        30



In [44]:
accuracy = accuracy_score(y_test , y_pred_test)
error = 1-accuracy
print('accuracy := ',accuracy," --- error := ",error)

accuracy :=  0.8666666666666667  --- error :=  0.1333333333333333


In [47]:
c_matrix = confusion_matrix(y_test,y_pred_test)
print(c_matrix)
px.density_heatmap(c_matrix)

[[10  0  0]
 [ 0  7  2]
 [ 0  2  9]]
